# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``
# For python 2.7 etc, either edit below, i.e. python=2.7 or
# ```
#    conda create --name <myEnvName> python=2.7
#    conda env update --name <myEnvName> --file environment.yml
# ```

name: catkit
dependencies:
  - astropy>=1.3
  - numpy>=1.15.0
  - conda-forge::pyusb
  - flake8
  - h5py
  - matplotlib
  - conda-forge::photutils
  - pip
  - psutil
  - pyserial
  - pysnmp
  - pytest
  - python=3.7.6
  - conda-forge::pyvisa>=1.10
  - conda-forge::pyvisa-py
  - requests
  - scipy
  - sphinx
  - pip:
    - --no-binary
    - --no-build-isolation
    - -r file:requirements.txt
