# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``
# For python 2.7 etc, either edit below, i.e. python=2.7 or
# ```
#    conda create --name <myEnvName> python=2.7
#    conda env update --name <myEnvName> --file environment.yml
# ```

name: catkit
dependencies:
  - cryptography=3.3.1
  - flake8=3.8.4
  - hypothesis=6.6.1
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - libtiff=4.1.0
  - sphinx=3.5.2
  - sqlite=3.33.0
  - toml=0.10.1
  - zipp=3.4.0
  - zope.interface=5.2.0
  - conda-forge::astropy>=1.3
  - conda-forge::numpy>=1.19.2  # See CATKIT-91
  - conda-forge::numexpr  # See CATKIT-91
  - conda-forge::pyusb
  - flake8
  - future  # See CATKIT-91
  - h5py
  - matplotlib
  - conda-forge::photutils=1.0.2  # See CATKIT-91
  - pip
  - psutil
  - pyserial
  - pysnmp
  - pytest
  - python=3.7.6
  - conda-forge::pyvisa>=1.10
  - conda-forge::pyvisa-py
  - requests
  - conda-forge::scipy  # See CATKIT-91
  - sphinx
  - conda-forge::xxhash  # See CATKIT-91
  - pip:
    - zwoasi>=0.0.21 # Requires additional manual install of driver(s) from https://astronomy-imaging-camera.com/software-drivers
    - ftd2xx # Requires additional manual install of driver from https://www.ftdichip.com/Drivers/D2XX.htm
    - hcipy
    - git+https://github.com/spacetelescope/poppy.git@v0.9.2
